import React,{useEffect,useMemo,useState} from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {
  Heart,Home,Search,Calendar,Clock3,Pill,CreditCard,User,Bell,LogOut,Menu,X,
  ChevronLeft,ChevronRight,Check,CheckCircle2,AlertTriangle,Shield,Eye,EyeOff,
  Edit3,Trash2,Hospital,Plus,Minus,FileText,ArrowRight
} from 'lucide-react';
import api from './api';
import './index.css';

const HOSPITALS=['MediLink General Hospital','City Care Hospital','Central Medical Centre'];
const SPECIALTIES=['Cardiology','General Medicine','Dermatology','Pediatrics','Orthopedics'];
const TIMES=['09:00 AM','10:00 AM','11:00 AM','01:00 PM','02:00 PM','03:00 PM','04:30 PM'];

const I={logo:Heart,home:Home,search:Search,calendar:Calendar,clock:Clock3,pill:Pill,card:CreditCard,user:User,bell:Bell,logout:LogOut,menu:Menu,close:X,chevronLeft:ChevronLeft,chevronRight:ChevronRight,check:Check,checkCircle:CheckCircle2,alertTriangle:AlertTriangle,shield:Shield,eye:Eye,eyeOff:EyeOff,edit:Edit3,trash:Trash2,hospital:Hospital,plus:Plus,minus:Minus,doc:FileText,arrowRight:ArrowRight};
function Icon({name,size=20}){const C=I[name]||Heart;return <C size={size} strokeWidth={1.8}/>}

function Button({children,variant='primary',lg=false,sm=false,block=false,icon,iconRight,disabled,onClick,type='button'}){
 return <button type={type} disabled={disabled} onClick={onClick} className={`btn btn-${variant}${lg?' btn-lg':''}${sm?' btn-sm':''}${block?' btn-block':''}`}>{icon&&<Icon name={icon} size={17}/>}<span>{children}</span>{iconRight&&<Icon name={iconRight} size={17}/>}</button>
}
function Badge({status}){
 const m={available:['b-avail','✓','Available'],limited:['b-limited','⚠','Limited availability'],unavailable:['b-unavail','✕','Unavailable'],Confirmed:['b-avail','✓','Confirmed'],Completed:['b-info','✓','Completed'],Cancelled:['b-neutral','✕','Cancelled'],'Pending Payment':['b-limited','⚠','Pending Payment'],Paid:['b-avail','✓','Paid'],Refunded:['b-info','↺','Refunded'],Unpaid:['b-limited','⚠','Unpaid']}[status]||['b-neutral','●',status];
 return <span className={`badge ${m[0]}`}>{m[1]} {m[2]}</span>
}
function MedBadge({status}){return <Badge status={status==='available'?'available':status==='limited'?'limited':'unavailable'}/>}

function Brand({size=24}){return <div className="row" style={{gap:9}}><span style={{color:'var(--teal)'}}><Icon name="logo" size={size}/></span><span style={{fontFamily:'var(--font-display)',fontWeight:800,fontSize:size-4}}>MediLink</span></div>}
function Field({label,children,hint,error}){return <div className="field"><label>{label}</label>{children}{hint&&<span className="hint">{hint}</span>}{error&&<span className="error"><Icon name="alertTriangle" size={14}/> {error}</span>}</div>}
function TextInput({type='text',placeholder,value,onChange}){return <input className="input" type={type} placeholder={placeholder} value={value} onChange={e=>onChange?.(e.target.value)}/>}

function useAuth(){
 const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('medilink_user'))}catch{return null}});
 const login=u=>{setUser(u);localStorage.setItem('medilink_user',JSON.stringify(u))};
 const logout=()=>{setUser(null);localStorage.removeItem('medilink_user');localStorage.removeItem('medilink_token')};
 return {user,login,logout};
}

function AuthWrap({children,wide=false,onBack}){return <div className="auth-wrap"><div className={`auth-card${wide?' wide':''}`}>{onBack&&<button type="button" className="btn btn-ghost btn-sm" style={{marginBottom:20}} onClick={onBack} aria-label="Go back to the previous page"><Icon name="chevronLeft" size={17}/><span>Back</span></button>}{children}</div></div>}

function App(){
 const {user,login,logout}=useAuth();
 const [view,setView]=useState(user?(user.role==='doctor'?'doctorDashboard':user.role==='staff'?'staffDashboard':'patientDashboard'):'landing');
 const [stack,setStack]=useState([]);
 const [drawer,setDrawer]=useState(false);
 const [toast,setToast]=useState('');
 const [selectedDoctor,setSelectedDoctor]=useState(null);
 const [booking,setBooking]=useState({date:null,time:null});
 const [activeAppt,setActiveAppt]=useState(null);

 const nav=(v,push=true)=>{if(push)setStack(s=>[...s,view]);setView(v);setDrawer(false);window.scrollTo(0,0)};
 const back=()=>{setStack(s=>{const a=[...s];setView(a.pop()||'patientDashboard');return a})};
 const showToast=m=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const openDoctor=d=>{setSelectedDoctor(d);setBooking({date:d.slots?.[0]?.date||null,time:null});nav('doctorDetails')};

 const loginUser=(u,t)=>{localStorage.setItem('medilink_token',t);login(u);setView(u.role==='doctor'?'doctorDashboard':u.role==='staff'?'staffDashboard':'patientDashboard')};
 const doLogout=()=>{logout();setStack([]);setView('landing');showToast('You have been logged out.')};

 useEffect(()=>{if(user && view==='landing')setView(user.role==='doctor'?'doctorDashboard':user.role==='staff'?'staffDashboard':'patientDashboard')},[]);

 if(!user){
  if(view==='landing') return <><Landing nav={nav}/><Toast text={toast}/></>;
  if(view==='login') return <><Login nav={nav} loginUser={loginUser}/><Toast text={toast}/></>;
  if(view==='register') return <><Register nav={nav} loginUser={loginUser}/><Toast text={toast}/></>;
  if(view==='portalSelect') return <><PortalSelect nav={nav}/><Toast text={toast}/></>;
  if(view==='doctorLogin') return <><RoleLogin role="doctor" nav={nav} loginUser={loginUser}/><Toast text={toast}/></>;
  if(view==='staffLogin') return <><RoleLogin role="staff" nav={nav} loginUser={loginUser}/><Toast text={toast}/></>;
 }

 const common={user,nav,back,canGoBack:stack.length>0,drawer,setDrawer,doLogout,showToast,selectedDoctor,setSelectedDoctor,booking,setBooking,activeAppt,setActiveAppt,openDoctor};
 let content;
 if(view==='patientDashboard') content=<PatientDashboard {...common}/>;
 else if(view==='findDoctor') content=<FindDoctor {...common}/>;
 else if(view==='doctorResults') content=<DoctorResults {...common}/>;
 else if(view==='doctorDetails') content=<DoctorDetails {...common}/>;
 else if(view==='selectSlot') content=<SelectSlot {...common}/>;
 else if(view==='appointmentSummary') content=<AppointmentSummary {...common}/>;
 else if(view==='patientDetails') content=<PatientDetails {...common}/>;
 else if(view==='payment') content=<Payment {...common}/>;
 else if(view==='paymentSuccess') content=<PaymentSuccess {...common}/>;
 else if(view==='medicineSearch') content=<MedicineSearch {...common}/>;
 else if(view==='medicineResults') content=<MedicineResults {...common}/>;
 else if(view==='myAppointments') content=<MyAppointments {...common}/>;
 else if(view==='appointmentDetails') content=<AppointmentDetails {...common}/>;
 else if(view==='reschedule') content=<Reschedule {...common}/>;
 else if(view==='patientPayments') content=<PatientPayments {...common}/>;
 else if(view==='profile') content=<Profile {...common}/>;
 else if(view==='doctorDashboard') content=<DoctorDashboard {...common}/>;
 else if(view==='doctorAvailability') content=<DoctorAvailability {...common}/>;
 else if(view==='doctorSchedule') content=<DoctorSchedule {...common}/>;
 else if(view==='staffDashboard') content=<StaffDashboard {...common}/>;
 else if(view==='staffDoctors') content=<StaffDoctors {...common}/>;
 else if(view==='staffMedicine') content=<StaffMedicine {...common}/>;
 else if(view==='staffAppointments') content=<StaffAppointments {...common}/>;
 else content=<PatientDashboard {...common}/>;
 return <><Shell role={user.role} active={view} title={titleFor(view)} {...common}>{content}</Shell><Toast text={toast}/></>;
}

function titleFor(v){return ({patientDashboard:'Dashboard',findDoctor:'Find a Doctor',doctorResults:'Search Results',doctorDetails:'Doctor Details',selectSlot:'Select Appointment Slot',appointmentSummary:'Appointment Summary',patientDetails:'Patient Details',payment:'Payment',paymentSuccess:'Payment Confirmation',medicineSearch:'Medicine Availability',medicineResults:'Medicine Results',myAppointments:'My Appointments',appointmentDetails:'Appointment Details',reschedule:'Reschedule Appointment',patientPayments:'Payments',profile:'Profile',doctorDashboard:'Doctor Dashboard',doctorAvailability:'Manage Availability',doctorSchedule:'Appointment Schedule',staffDashboard:'Staff Dashboard',staffDoctors:'Manage Doctors',staffMedicine:'Manage Medicine Availability',staffAppointments:'Appointment & Payment Management'})[v]||'MediLink'}

function navItems(role){
 if(role==='doctor')return [['doctorDashboard','Dashboard','home'],['doctorAvailability','Availability','calendar'],['doctorSchedule','Appointments','clock'],['profile','Profile','user']];
 if(role==='staff')return [['staffDashboard','Dashboard','home'],['staffDoctors','Doctors','user'],['staffMedicine','Medicine','pill'],['staffAppointments','Appointments & Payments','card'],['profile','Profile','user']];
 return [['patientDashboard','Dashboard','home'],['findDoctor','Find Doctor','search'],['myAppointments','My Appointments','calendar'],['medicineSearch','Medicine','pill'],['patientPayments','Payments','card'],['profile','Profile','user']];
}
function Shell({role,active,title,user,nav,back,canGoBack,drawer,setDrawer,doLogout,children}){
 const items=navItems(role);
 return <div className="app-shell">
  <aside className="sidebar"><div className="side-logo"><Brand size={24}/></div><div className="side-nav">{items.map(([v,l,i])=><button key={v} className={`nav-item ${active===v?'active':''}`} onClick={()=>nav(v)}><Icon name={i} size={19}/><span>{l}</span></button>)}</div>
   <div className="side-foot"><div className="row" style={{padding:'8px 12px'}}><span className="avatar" style={{width:34,height:34,borderRadius:10,fontSize:13}}>{user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><div className="h-sm" style={{fontSize:13.5}}>{user.name}</div><div className="small muted" style={{textTransform:'capitalize'}}>{role}</div></div></div><button className="nav-item" onClick={doLogout}><Icon name="logout" size={19}/><span>Logout</span></button></div>
  </aside>
  <div className="main-col">
   <div className="topbar"><button className="btn btn-icon btn-ghost" onClick={()=>setDrawer(true)}><Icon name="menu" size={20}/></button><Brand size={21}/><button className="btn btn-icon btn-ghost" onClick={()=>nav('profile')}><Icon name="user" size={20}/></button></div>
  <div className="page-head"><div className="row" style={{alignItems:'flex-start',gap:16}}>{canGoBack&&<button type="button" className="btn btn-ghost btn-sm" onClick={back} aria-label="Go back to the previous page"><Icon name="chevronLeft" size={17}/><span>Back</span></button>}<div><span className="eyebrow">{role.toUpperCase()} PORTAL</span><h1 className="h-lg">{title}</h1></div></div></div>
   <div className="page-body">{children}</div>
  </div>
  {drawer&&<div className="drawer-overlay" onClick={e=>e.target===e.currentTarget&&setDrawer(false)}><div className="drawer"><div className="row between"><Brand size={22}/><button className="btn btn-icon btn-ghost" onClick={()=>setDrawer(false)}><Icon name="close"/></button></div><div className="side-nav">{items.map(([v,l,i])=><button key={v} className={`nav-item ${active===v?'active':''}`} onClick={()=>nav(v)}><Icon name={i} size={19}/><span>{l}</span></button>)}</div><div className="side-foot"><button className="nav-item" onClick={doLogout}><Icon name="logout" size={19}/><span>Logout</span></button></div></div></div>}
 </div>
}

function Toast({text}){return text?<div className="toast-stack"><div className="toast">{text}</div></div>:null}

function Landing({nav}){const f=[['search','Find available doctors','Search by specialty and hospital, and see real-time availability before you book.'],['calendar','Book appointments','Pick a date and time that suits you, then confirm in a few simple steps.'],['pill','Check medicine availability','See whether the medicine you need is in stock before you travel to the hospital.'],['card','Secure online payment','Pay your appointment fee safely online and get instant confirmation.']];return <div style={{minHeight:'100vh'}}><div style={{background:'linear-gradient(180deg,var(--teal-tint),transparent 70%)'}}><div className="container" style={{padding:'18px 20px 0'}}><div className="row between"><Brand size={24}/><div className="row"><Button variant="ghost" sm onClick={()=>nav('login')}>Login</Button><Button sm onClick={()=>nav('register')}>Register</Button></div></div></div><div className="container center" style={{padding:'56px 20px 40px',maxWidth:720}}><span className="eyebrow">COMMUNITY HEALTHCARE, SIMPLIFIED</span><h1 className="h-xl" style={{marginTop:10}}>Reach a doctor, check your medicine, and pay - without the trip.</h1><p className="muted" style={{marginTop:14,fontSize:16}}>MediLink helps you find available doctors, book appointments, and check medicine stock at nearby hospitals, all from one simple place.</p><div className="row wrap" style={{justifyContent:'center',marginTop:26}}><Button lg icon="search" onClick={()=>nav('login')}>Find a Doctor</Button><Button lg variant="secondary" icon="pill" onClick={()=>nav('login')}>Check Medicine Availability</Button></div></div></div><div className="container" style={{padding:'10px 20px 60px'}}><div className="grid grid-4">{f.map(([i,t,x])=><div className="card-flat" key={t}><span style={{color:'var(--teal)'}}><Icon name={i} size={24}/></span><h3 className="h-sm" style={{marginTop:12}}>{t}</h3><p className="small muted" style={{marginTop:6}}>{x}</p></div>)}</div></div><div style={{borderTop:'1px solid var(--sand)',padding:18,textAlign:'center'}} className="small muted">For informational purposes only. Please confirm availability and appointment details with the hospital before visiting.</div></div>}
function Login({nav,loginUser}){const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [err,setErr]=useState('');const submit=async()=>{try{const r=await api.post('/auth/login',{email,password:pass});loginUser(r.data.user,r.data.token)}catch(e){setErr(e.response?.data?.message||'Login failed')}};return <AuthWrap onBack={()=>nav('landing')}><div className="center" style={{marginBottom:22}}><Brand size={28}/><p className="muted small" style={{marginTop:10}}>Log in to find doctors, book appointments, and check medicine availability.</p></div>{err&&<div className="alert alert-error" style={{marginBottom:14}}><Icon name="alertTriangle"/><span>{err}</span></div>}<Field label="Email address"><TextInput type="email" placeholder="you@example.com" value={email} onChange={setEmail}/></Field><Field label="Password"><TextInput type="password" placeholder="Enter your password" value={pass} onChange={setPass}/></Field><div className="row between" style={{margin:'-6px 0 18px'}}><span/><a href="#" className="small" style={{color:'var(--teal-deep)',fontWeight:600}} onClick={e=>{e.preventDefault();}}>Forgot password?</a></div><Button block lg onClick={submit}>Log in</Button><hr className="divider"/><p className="center small">Don't have an account? <a href="#" style={{color:'var(--teal-deep)',fontWeight:700}} onClick={e=>{e.preventDefault();nav('register')}}>Register</a></p><p className="center small muted" style={{marginTop:14}}>Doctor or hospital staff? <a href="#" style={{color:'var(--sky)',fontWeight:700}} onClick={e=>{e.preventDefault();nav('portalSelect')}}>Access your portal</a></p></AuthWrap>}

function Register({nav,loginUser}){const [f,setF]=useState({name:'',email:'',phone:'',password:'',confirm:''});const [err,setErr]=useState('');const set=(k,v)=>setF({...f,[k]:v});const submit=async()=>{if(f.password!==f.confirm)return setErr('Passwords do not match.');try{const r=await api.post('/auth/register',{name:f.name,email:f.email,phone:f.phone,password:f.password});loginUser(r.data.user,r.data.token)}catch(e){setErr(e.response?.data?.message||'Registration failed')}};return <AuthWrap onBack={()=>nav('landing')}><div className="center" style={{marginBottom:20}}><Brand size={28}/><p className="muted small" style={{marginTop:8}}>Create your MediLink account to get started.</p></div>{err&&<div className="alert alert-error" style={{marginBottom:14}}><Icon name="alertTriangle"/><span>{err}</span></div>}<Field label="Full name"><TextInput placeholder="e.g. Kasun Perera" value={f.name} onChange={v=>set('name',v)}/></Field><Field label="Email address"><TextInput type="email" placeholder="you@example.com" value={f.email} onChange={v=>set('email',v)}/></Field><Field label="Phone number"><TextInput placeholder="07X XXX XXXX" value={f.phone} onChange={v=>set('phone',v)}/></Field><Field label="Password"><TextInput type="password" placeholder="At least 6 characters" value={f.password} onChange={v=>set('password',v)}/></Field><Field label="Confirm password"><TextInput type="password" placeholder="Re-enter your password" value={f.confirm} onChange={v=>set('confirm',v)}/></Field><div className="checkbox-row" style={{marginBottom:20}}><input type="checkbox"/><span>I agree to the Terms of Service and Privacy Policy.</span></div><Button block lg onClick={submit}>Create account</Button><p className="center small" style={{marginTop:16}}>Already have an account? <a href="#" style={{color:'var(--teal-deep)',fontWeight:700}} onClick={e=>{e.preventDefault();nav('login')}}>Log in</a></p></AuthWrap>}

function PortalSelect({nav}){return <AuthWrap onBack={()=>nav('landing')}><div className="center" style={{marginBottom:20}}><Brand size={26}/><p className="muted small" style={{marginTop:8}}>Choose your portal to continue.</p></div><div className="stack">{[['user','Patient','Book appointments and check medicine','login'],['doc','Doctor','Manage your schedule and appointments','doctorLogin'],['hospital','Hospital Staff','Manage doctors, medicine and payments','staffLogin']].map(([i,t,x,v])=><button className="card-flat" style={{textAlign:'left'}} key={t} onClick={()=>nav(v)}><div className="row between"><div className="row"><Icon name={i} size={22}/><div><div className="h-sm">{t}</div><div className="small muted">{x}</div></div></div><Icon name="chevronRight"/></div></button>)}</div></AuthWrap>}
function RoleLogin({role,nav,loginUser}){const [email,setEmail]=useState(role==='doctor'?'doctor@medilink.com':'staff@medilink.com');const [pass,setPass]=useState(role==='doctor'?'Doctor123':'Staff123');const [err,setErr]=useState('');const submit=async()=>{try{const r=await api.post('/auth/login',{email,password:pass});loginUser(r.data.user,r.data.token)}catch(e){setErr(e.response?.data?.message||'Login failed')}};return <AuthWrap onBack={()=>nav('portalSelect')}><div className="center" style={{marginBottom:20}}><Brand size={26}/><p className="muted small" style={{marginTop:8}}>{role==='doctor'?'Doctor portal login':'Hospital staff portal login'}</p></div>{err&&<div className="alert alert-error">{err}</div>}<Field label={role==='doctor'?'Email address':'Staff email'}><TextInput type="email" value={email} onChange={setEmail}/></Field><Field label="Password"><TextInput type="password" value={pass} onChange={setPass}/></Field><Button block lg onClick={submit}>Log in</Button><p className="small muted center" style={{marginTop:14}}>Demo: <b>{email}</b> / <b>{pass}</b></p></AuthWrap>}

function PatientDashboard(p){const [a,setA]=useState([]);useEffect(()=>{api.get('/appointments').then(r=>setA(r.data)).catch(()=>{})},[]);const upcoming=a.find(x=>['Confirmed','Pending Payment'].includes(x.status));const services=[['search','Find a Doctor','Search by specialty or hospital','findDoctor'],['calendar','Book Appointment','Pick a date and time that suits you','findDoctor'],['pill','Check Medicine','See what is in stock before you visit','medicineSearch'],['clock','My Appointments','View, reschedule, or cancel visits','myAppointments']];return <><div className="card" style={{background:'linear-gradient(120deg,var(--teal-deep),var(--teal))',color:'#fff',border:'none',marginBottom:20}}><span className="eyebrow" style={{color:'#cfece7'}}>GOOD TO SEE YOU</span><h2 className="h-lg" style={{color:'#fff',marginTop:6}}>Hi {p.user.name.split(' ')[0]}, how can we help today?</h2><div className="row wrap" style={{marginTop:16}}><Button variant="ghost" icon="search" onClick={()=>p.nav('findDoctor')}>Find a Doctor</Button><Button variant="ghost" icon="pill" onClick={()=>p.nav('medicineSearch')}>Check Medicine</Button></div></div><h3 className="h-md" style={{marginBottom:12}}>Core services</h3><div className="grid grid-4" style={{marginBottom:24}}>{services.map(([i,t,x,v])=><button className="card-flat" style={{textAlign:'left'}} key={t} onClick={()=>p.nav(v)}><span style={{color:'var(--teal)'}}><Icon name={i} size={24}/></span><div className="h-sm" style={{marginTop:12}}>{t}</div><div className="small muted" style={{marginTop:4}}>{x}</div></button>)}</div><div className="grid grid-2"><div className="card-flat"><h3 className="h-sm">Upcoming appointment</h3>{upcoming?<div style={{marginTop:10}}><div className="row between wrap"><b>{upcoming.doctorName}</b><Badge status={upcoming.status}/></div><div className="small muted">{upcoming.specialty} • {upcoming.hospital}</div><div className="small" style={{marginTop:8}}>{upcoming.date} at {upcoming.time}</div><div style={{marginTop:14}}><Button sm onClick={()=>{p.setActiveAppt(upcoming);p.nav('appointmentDetails')}}>View details</Button></div></div>:<p className="small muted" style={{marginTop:10}}>You have no upcoming appointments. <a href="#" style={{color:'var(--teal-deep)',fontWeight:700}} onClick={e=>{e.preventDefault();p.nav('findDoctor')}}>Book one now</a>.</p>}</div><div className="card-flat"><h3 className="h-sm">Recent activity</h3>{a.slice(0,2).map(x=><div className="row between small" style={{marginTop:10}} key={x._id}><span>{x.doctorName}</span><Badge status={x.payment}/></div>)}</div></div></>}

function FindDoctor(p){const [q,setQ]=useState(''),[spec,setSpec]=useState(''),[hosp,setHosp]=useState('');const search=()=>{p.nav('doctorResults');p.setSearch?.({q,spec,hosp});localStorage.setItem('medilink_search',JSON.stringify({q,spec,hosp}))};return <div className="card-flat"><p className="small muted" style={{marginBottom:14}}>Search for doctors by name, specialty, or hospital, and see who is available now.</p><div className="grid grid-3"><Field label="Search"><TextInput placeholder="Doctor name (optional)" value={q} onChange={setQ}/></Field><Field label="Specialty"><select className="input" value={spec} onChange={e=>setSpec(e.target.value)}><option value="">All specialties</option>{SPECIALTIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Hospital"><select className="input" value={hosp} onChange={e=>setHosp(e.target.value)}><option value="">All hospitals</option>{HOSPITALS.map(x=><option key={x}>{x}</option>)}</select></Field></div><Button icon="search" onClick={search}>Search</Button><h3 className="h-sm" style={{margin:'24px 0 10px'}}>Popular specialties</h3><div className="chip-row">{SPECIALTIES.map(x=><button className="chip" key={x} onClick={()=>{localStorage.setItem('medilink_search',JSON.stringify({q:'',spec:x,hosp:''}));p.nav('doctorResults')}}>{x}</button>)}</div></div>}

function useDoctors(){const [d,setD]=useState([]);useEffect(()=>{api.get('/doctors').then(r=>setD(r.data)).catch(()=>{})},[]);return d}
function DoctorResults(p){const all=useDoctors();const f=JSON.parse(localStorage.getItem('medilink_search')||'{}');const r=all.filter(d=>(!f.q||d.name.toLowerCase().includes(f.q.toLowerCase())||d.specialty.toLowerCase().includes(f.q.toLowerCase()))&&(!f.spec||d.specialty===f.spec)&&(!f.hosp||d.hospital===f.hosp));return <><div className="row between wrap" style={{marginBottom:14}}><p className="small muted">{r.length} doctor{r.length===1?'':'s'} found.</p><Button variant="ghost" sm icon="search" onClick={()=>p.nav('findDoctor')}>Refine search</Button></div><div className="stack">{r.map(d=><div className="doc-card" key={d._id}><div className="avatar">{d.initials}</div><div style={{flex:1}}><div className="row between wrap"><div><div className="h-sm">{d.name}</div><div className="small muted">{d.specialty} • {d.hospital}</div></div><Badge status={d.status}/></div><div className="small" style={{marginTop:8}}>Next available: {d.next}</div><div className="row" style={{marginTop:12}}><Button sm variant="ghost" onClick={()=>p.openDoctor(d)}>View details</Button><Button sm disabled={d.status==='unavailable'} onClick={()=>{p.openDoctor(d);p.nav('selectSlot')}}>Book appointment</Button></div></div></div>)}</div></>}

function DoctorDetails(p){const d=p.selectedDoctor;return <div className="card-flat"><div className="row"><div className="avatar" style={{width:64,height:64,fontSize:20}}>{d.initials}</div><div><h2 className="h-lg">{d.name}</h2><div className="small muted">{d.specialty} • {d.hospital}</div><div style={{marginTop:8}}><Badge status={d.status}/></div></div></div><hr className="divider"/><h3 className="h-sm">About</h3><p className="small" style={{marginTop:6}}>{d.bio}</p><hr className="divider"/><div className="row between wrap"><div><div className="small muted">Consultation fee</div><div className="h-md">Rs. {d.fee?.toLocaleString()}</div></div><div><div className="small muted">Next available</div><div className="h-sm">{d.next}</div></div></div><div style={{marginTop:22}}><Button lg block disabled={d.status==='unavailable'} onClick={()=>p.nav('selectSlot')}>Book Appointment</Button></div></div>}

function Pulse({index}){const steps=['Doctor','Slot','Summary','Details','Payment','Done'];return <div className="pulse-track">{steps.map((s,i)=><React.Fragment key={s}><div className="pulse-node-wrap"><div className={`pulse-node ${i<index?'done':i===index?'active':''}`}/><span className={`pulse-label ${i<=index?'on':''}`}>{s}</span></div>{i<steps.length-1&&<div className="pulse-seg"><svg viewBox="0 0 100 22" preserveAspectRatio="none"><path className="pulse-line-todo" d="M0 11 H100" strokeWidth="2" fill="none"/>{i===index?<path className="pulse-beat" d="M0 11 H30 L38 3 L46 19 L54 11 H100" strokeWidth="2.3" fill="none"/>:<path className={i<index?'pulse-line-done':'pulse-line-todo'} d="M0 11 H100" strokeWidth="2" fill="none"/>}</svg></div>}</React.Fragment>)}</div>}

function SelectSlot(p){const d=p.selectedDoctor;const date=p.booking.date||d.slots?.[0]?.date;const times=d.slots?.find(x=>x.date===date)?.times||[];return <><Pulse index={1}/><div className="card-flat" style={{marginTop:18}}><div className="row between"><div><b>{d.name}</b><div className="small muted">{d.specialty} • {d.hospital}</div></div><Badge status={d.status}/></div><hr className="divider"/><h3 className="h-sm">Select a date</h3><div className="chip-row" style={{marginTop:10}}>{(d.slots||[]).map(x=><button className={`chip ${date===x.date?'selected':''}`} key={x.date} onClick={()=>p.setBooking({date:x.date,time:null})}>{x.date}</button>)}</div><h3 className="h-sm" style={{marginTop:20}}>Select a time</h3><div className="chip-row" style={{marginTop:10}}>{TIMES.map(t=><button className={`chip ${p.booking.time===t?'selected':''}`} disabled={!times.includes(t)} key={t} onClick={()=>p.setBooking({...p.booking,date,time:t})}>{t}</button>)}</div><div className="row" style={{marginTop:24}}><Button lg disabled={!p.booking.time} onClick={()=>p.nav('appointmentSummary')}>Continue</Button><Button variant="ghost" onClick={p.back}>Back</Button></div></div></>}

function SummaryRows({rows}){return <div className="stack">{rows.map(([a,b])=><div className="row between" key={a}><span className="small muted">{a}</span><span className="small" style={{fontWeight:700}}>{b}</span></div>)}</div>}
function AppointmentSummary(p){const d=p.selectedDoctor;return <><Pulse index={2}/><div className="card-flat" style={{marginTop:18}}><h3 className="h-sm">Appointment summary</h3><SummaryRows rows={[['Doctor',d.name],['Specialty',d.specialty],['Hospital',d.hospital],['Date',p.booking.date],['Time',p.booking.time],['Appointment fee',`Rs. ${d.fee?.toLocaleString()}`]]}/><div className="row" style={{marginTop:22}}><Button lg onClick={()=>p.nav('patientDetails')}>Confirm Appointment</Button><Button variant="ghost" onClick={p.back}>Back / Edit</Button></div></div></>}

function PatientDetails(p){const [f,setF]=useState({name:p.user.name,phone:p.user.phone||'',email:p.user.email});const d=p.selectedDoctor;return <><Pulse index={3}/><div className="grid grid-2" style={{marginTop:18,alignItems:'start'}}><div className="card-flat"><h3 className="h-sm">Your details</h3><Field label="Full name"><TextInput value={f.name} onChange={v=>setF({...f,name:v})}/></Field><Field label="Phone number"><TextInput value={f.phone} onChange={v=>setF({...f,phone:v})}/></Field><Field label="Email address"><TextInput type="email" value={f.email} onChange={v=>setF({...f,email:v})}/></Field><Button lg block onClick={()=>{p.setPatientDetails?.(f);p.nav('payment')}}>Continue to Payment</Button></div><div className="card-flat"><h3 className="h-sm">Appointment summary</h3><SummaryRows rows={[['Doctor',d.name],['Hospital',d.hospital],['Date',p.booking.date],['Time',p.booking.time],['Fee',`Rs. ${d.fee?.toLocaleString()}`]]}/></div></div></>}

function Payment(p){const [method,setMethod]=useState('card');const [num,setNum]=useState('');const [err,setErr]=useState('');const d=p.selectedDoctor;const pay=async()=>{try{const r=await api.post('/appointments',{doctorId:d._id,date:p.booking.date,time:p.booking.time});p.setActiveAppt(r.data);p.nav('paymentSuccess')}catch(e){setErr(e.response?.data?.message||'Payment failed')}};return <><Pulse index={4}/><div className="grid grid-2" style={{marginTop:18,alignItems:'start'}}><div className="card-flat"><div className="row between"><h3 className="h-sm">Payment method</h3><Icon name="shield"/></div><div className="row wrap" style={{marginTop:10}}><button className={`chip ${method==='card'?'selected':''}`} onClick={()=>setMethod('card')}>Card</button><button className={`chip ${method==='bank'?'selected':''}`} onClick={()=>setMethod('bank')}>Online Banking</button></div>{method==='card'?<><Field label="Cardholder name"><TextInput placeholder="Name on card"/></Field><Field label="Card number" hint="Demo payment: card details are optional."><TextInput placeholder="1234 5678 9012 3456" value={num} onChange={setNum}/></Field><div className="grid grid-2"><Field label="Expiry date"><TextInput placeholder="MM/YY"/></Field><Field label="CVV"><TextInput type="password" placeholder="123"/></Field></div></>:<><Field label="Select your bank"><select className="input"><option>Bank of Ceylon</option><option>Commercial Bank</option><option>Sampath Bank</option><option>HNB</option></select></Field><Field label="Account holder name"><TextInput placeholder="Full name as per bank account"/></Field></>}{err&&<div className="alert alert-error">{err}</div>}<div className="alert alert-info" style={{margin:'6px 0 18px'}}><Icon name="shield"/><span>Your payment information is encrypted and protected. MediLink never stores your full card details.</span></div><Button lg icon="shield" onClick={pay}>Pay Now</Button></div><div className="card-flat"><h3 className="h-sm">Order summary</h3><SummaryRows rows={[['Doctor',d.name],['Hospital',d.hospital],['Date & time',`${p.booking.date}, ${p.booking.time}`]]}/><hr className="divider"/><div className="row between"><span className="h-sm">Total</span><span className="h-md">Rs. {d.fee?.toLocaleString()}</span></div></div></div></>}

function PaymentSuccess(p){const a=p.activeAppt;return <div className="card-flat center" style={{maxWidth:480,margin:'10px auto',padding:'36px 28px'}}><span style={{color:'var(--moss)'}}><Icon name="checkCircle" size={52}/></span><h2 className="h-lg" style={{marginTop:14}}>Appointment Confirmed</h2><p className="small muted" style={{marginTop:6}}>Your appointment has been confirmed.</p><div className="card-flat" style={{textAlign:'left',marginTop:22,background:'var(--paper)'}}><SummaryRows rows={[['Confirmation number',a?.confirmationNumber||a?.confirmation||'MED-00000'],['Doctor',a?.doctorName||p.selectedDoctor?.name],['Hospital',a?.hospital||p.selectedDoctor?.hospital],['Date & time',`${a?.date||p.booking.date}, ${a?.time||p.booking.time}`],['Amount paid',`Rs. ${(a?.fee||p.selectedDoctor?.fee)?.toLocaleString()}`],['Payment status','Paid']]}/></div><div className="row wrap" style={{marginTop:22,justifyContent:'center'}}><Button onClick={()=>p.nav('appointmentDetails')}>View Appointment</Button><Button variant="ghost" onClick={()=>{p.setStack?.([]);p.nav('patientDashboard',false)}}>Back to Dashboard</Button></div></div>}

function MedicineSearch(p){const [q,setQ]=useState(''),[h,setH]=useState('All Hospitals');const search=()=>{localStorage.setItem('medilink_medsearch',JSON.stringify({q,h}));p.nav('medicineResults')};return <div className="card-flat"><div className="row" style={{marginBottom:14}}><Icon name="pill"/><p className="small muted">Check medicine availability before visiting the hospital.</p></div><div className="grid grid-3"><Field label="Medicine name"><TextInput placeholder="e.g. Paracetamol" value={q} onChange={setQ}/></Field><Field label="Hospital / pharmacy"><select className="input" value={h} onChange={e=>setH(e.target.value)}><option>All Hospitals</option>{HOSPITALS.map(x=><option key={x}>{x}</option>)}</select></Field><div className="field" style={{justifyContent:'flex-end'}}><Button lg icon="search" onClick={search}>Search</Button></div></div></div>}
function MedicineResults(p){const [r,setR]=useState([]);const f=JSON.parse(localStorage.getItem('medilink_medsearch')||'{}');useEffect(()=>{api.get('/medicines',{params:{q:f.q||'',hospital:f.h||'All Hospitals'}}).then(x=>setR(x.data))},[]);return <><div className="row between wrap" style={{marginBottom:14}}><p className="small muted">{r.length} result{r.length===1?'':'s'}.</p><Button variant="ghost" sm onClick={()=>p.nav('medicineSearch')}>New search</Button></div><div className="stack">{r.map(m=><div className="card-flat" key={m._id}><div className="row between wrap"><div><div className="h-sm">{m.name}</div><div className="small muted">{m.hospital}</div></div><MedBadge status={m.status}/></div><div className="row between" style={{marginTop:10}}><span className="small">{m.stock}</span><span className="small muted">Updated {m.updated}</span></div></div>)}</div></>}

function MyAppointments(p){const [r,setR]=useState([]);const load=()=>api.get('/appointments').then(x=>setR(x.data));useEffect(()=>{load()},[]);const cancel=async(id)=>{await api.patch(`/appointments/${id}/cancel`);load()};return <><h3 className="h-sm" style={{marginBottom:10}}>Upcoming</h3><div className="stack" style={{marginBottom:26}}>{r.filter(a=>['Confirmed','Pending Payment'].includes(a.status)).map(a=><div className="appt-card" key={a._id}><div className="row between wrap"><div><div className="h-sm">{a.doctorName}</div><div className="small muted">{a.specialty} • {a.hospital}</div></div><Badge status={a.status}/></div><div className="small" style={{marginTop:8}}>{a.date} at {a.time}</div><div className="row wrap" style={{marginTop:12}}><Button sm variant="ghost" onClick={()=>{p.setActiveAppt(a);p.nav('appointmentDetails')}}>View Details</Button>{a.status==='Confirmed'&&<Button sm variant="danger-ghost" onClick={()=>cancel(a._id)}>Cancel</Button>}</div></div>)}</div><h3 className="h-sm" style={{marginBottom:10}}>Previous</h3><div className="stack">{r.filter(a=>['Completed','Cancelled'].includes(a.status)).map(a=><div className="appt-card" key={a._id}><div className="row between"><b>{a.doctorName}</b><Badge status={a.status}/></div><div className="small muted">{a.date} at {a.time}</div></div>)}</div></>}
function AppointmentDetails(p){const a=p.activeAppt;return <div className="card-flat" style={{maxWidth:560}}><div className="row between"><h3 className="h-md">{a?.doctorName}</h3><Badge status={a?.status}/></div><div className="small muted">{a?.specialty}</div><hr className="divider"/><SummaryRows rows={[['Hospital',a?.hospital],['Date',a?.date],['Time',a?.time],['Appointment status',a?.status],['Payment status',a?.payment],['Amount',`Rs. ${a?.fee?.toLocaleString()}`]]}/>{a?.status==='Confirmed'&&<div className="row" style={{marginTop:22}}><Button variant="danger-ghost" onClick={async()=>{await api.patch(`/appointments/${a._id}/cancel`);p.nav('myAppointments',false)}}>Cancel Appointment</Button></div>}</div>}
function Reschedule(){return <div className="card-flat" style={{maxWidth:560}}><h3 className="h-md">Reschedule Appointment</h3><p className="small muted" style={{marginTop:8}}>Choose a new slot from the doctor's current availability. This full workflow is backed by the appointment API; connect the slot update endpoint to enable provider-specific rescheduling rules.</p></div>}
function PatientPayments(p){const [r,setR]=useState([]);useEffect(()=>{api.get('/appointments').then(x=>setR(x.data))},[]);return <div className="table-wrap"><table><thead><tr><th>Appointment</th><th>Doctor</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{r.map(a=><tr key={a._id}><td style={{fontFamily:'var(--font-mono)'}}>{a._id.slice(-8)}</td><td>{a.doctorName}</td><td>{a.date}</td><td>Rs. {a.fee?.toLocaleString()}</td><td><Badge status={a.payment}/></td></tr>)}</tbody></table></div>}
function Profile(p){const [name,setName]=useState(p.user.name);return <div className="card-flat" style={{maxWidth:480}}><Field label="Full name"><TextInput value={name} onChange={setName}/></Field><Field label="Email address"><TextInput value={p.user.email} onChange={()=>{}}/></Field>{p.user.role==='patient'&&<Field label="Phone number"><TextInput value={p.user.phone||''} onChange={()=>{}}/></Field>}<div className="row"><Button onClick={()=>p.showToast('Profile updated.')}>Save Changes</Button><Button variant="danger-ghost" icon="logout" onClick={p.doLogout}>Logout</Button></div></div>}

function Stat({icon,n,label,color}){return <div className="card-flat"><span style={{color:`var(--${color})`}}><Icon name={icon} size={22}/></span><div className="h-lg" style={{marginTop:10}}>{n}</div><div className="small muted">{label}</div></div>}
function DoctorDashboard(p){const [r,setR]=useState([]);useEffect(()=>{api.get('/appointments').then(x=>setR(x.data))},[]);return <><div className="grid grid-3" style={{marginBottom:20}}><Stat icon="calendar" n={r.length} label="Appointments" color="teal"/><Stat icon="clock" n={r.filter(x=>x.status==='Confirmed').length} label="Confirmed" color="sky"/><Stat icon="checkCircle" n="Open" label="Availability" color="moss"/></div><div className="card-flat"><h3 className="h-sm">Quick actions</h3><div className="row wrap" style={{marginTop:12}}><Button variant="secondary" onClick={()=>p.nav('doctorAvailability')}>Manage Availability</Button><Button variant="secondary" onClick={()=>p.nav('doctorSchedule')}>View Appointments</Button></div></div></>}
function DoctorAvailability(p){const [d,setD]=useState(p.selectedDoctor?.slots||[]);const all=['09:00 AM','10:00 AM','11:00 AM','01:00 PM','02:00 PM','03:00 PM','04:30 PM'];return <div className="card-flat"><p className="small muted">Tap a time slot to mark it available or unavailable.</p>{d.map((day,idx)=><div style={{marginTop:20}} key={day.date}><h3 className="h-sm">{day.date}</h3><div className="chip-row" style={{marginTop:10}}>{all.map(t=>{const on=day.times.includes(t);return <button className={`chip ${on?'selected':''}`} key={t} onClick={()=>setD(d.map((x,i)=>i===idx?{...x,times:on?x.times.filter(y=>y!==t):[...x.times,t]}:x))}>{on?'✓ ':''}{t}</button>})}</div></div>)}<div style={{marginTop:26}}><Button lg onClick={()=>p.showToast('Availability updated.')}>Update Availability</Button></div></div>}
function DoctorSchedule(p){const [r,setR]=useState([]);useEffect(()=>{api.get('/appointments').then(x=>setR(x.data))},[]);return <div className="table-wrap"><table><thead><tr><th>Patient</th><th>Date</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>{r.map(a=><tr key={a._id}><td>{a.patient?.name||'Patient'}</td><td>{a.date}</td><td>{a.time}</td><td><Badge status={a.status}/></td><td><Button sm variant="ghost" onClick={()=>p.showToast('Appointment selected.')}>View</Button></td></tr>)}</tbody></table></div>}
function StaffDashboard(p){const [d,setD]=useState([]),[m,setM]=useState([]);useEffect(()=>{api.get('/doctors').then(x=>setD(x.data));api.get('/medicines').then(x=>setM(x.data))},[]);return <><div className="grid grid-4" style={{marginBottom:20}}><Stat icon="user" n={d.length} label="Total doctors" color="teal"/><Stat icon="checkCircle" n={d.filter(x=>x.status!=='unavailable').length} label="Available doctors" color="moss"/><Stat icon="calendar" n="Live" label="Appointments" color="sky"/><Stat icon="pill" n={m.filter(x=>x.status==='available').length} label="Medicines in stock" color="amber"/></div><div className="card-flat"><h3 className="h-sm">Quick actions</h3><div className="row wrap" style={{marginTop:12}}><Button variant="secondary" onClick={()=>p.nav('staffDoctors')}>Manage Doctors</Button><Button variant="secondary" onClick={()=>p.nav('staffMedicine')}>Manage Medicine</Button><Button variant="secondary" onClick={()=>p.nav('staffAppointments')}>Appointments & Payments</Button></div></div></>}
function StaffDoctors(){const d=useDoctors();return <div className="table-wrap"><table><thead><tr><th>Doctor</th><th>Specialty</th><th>Hospital</th><th>Availability</th><th>Status</th></tr></thead><tbody>{d.map(x=><tr key={x._id}><td>{x.name}</td><td>{x.specialty}</td><td>{x.hospital}</td><td>{x.next}</td><td><Badge status={x.status}/></td></tr>)}</tbody></table></div>}
function StaffMedicine(p){const [r,setR]=useState([]);const load=()=>api.get('/medicines').then(x=>setR(x.data));useEffect(()=>{load()},[]);const cycle=async m=>{const order=['available','limited','unavailable'];const s=order[(order.indexOf(m.status)+1)%3];await api.patch(`/medicines/${m._id}`,{status:s,stock:s==='available'?'In stock':s==='limited'?'Low stock':'Out of stock'});load();p.showToast('Medicine updated.')};return <div className="table-wrap"><table><thead><tr><th>Medicine</th><th>Hospital</th><th>Availability</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{r.map(m=><tr key={m._id}><td>{m.name}</td><td>{m.hospital}</td><td><MedBadge status={m.status}/></td><td>{m.stock}</td><td><Button sm variant="ghost" onClick={()=>cycle(m)}>Update</Button></td></tr>)}</tbody></table></div>}
function StaffAppointments(p){const [r,setR]=useState([]);useEffect(()=>{api.get('/appointments').then(x=>setR(x.data))},[]);return <div className="table-wrap"><table><thead><tr><th>ID</th><th>Doctor</th><th>Date</th><th>Time</th><th>Payment</th><th>Status</th></tr></thead><tbody>{r.map(a=><tr key={a._id}><td>{a._id.slice(-8)}</td><td>{a.doctorName}</td><td>{a.date}</td><td>{a.time}</td><td><Badge status={a.payment}/></td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div>}

ReactDOM.createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
